#!/usr/bin/bash

#install git
apt-get update
apt-get install git

#install emacs
apt-get install emacs

#install nginx
apt-get install -y nginx
service nginx restart

#install mysql-server
apt-get install -y mysql-server
apt-get update
#install python3 and nodejs
apt-get install -y python3

apt-get install -y nodejs

#install nettools
apt-get install -y net-tools

#install curl
apt install curl

#install puppet
apt-get install -y ruby=1:2.7+1 --allow-downgrades
apt-get install -y ruby-augeas
apt-get install -y ruby-shadow
apt-get install -y puppet
gem install puppet-lint

apt-get update
#install pip3
apt install python3-pip

#install fabric v1.14
apt-get install libffi-dev
apt-get install libssl-dev
apt-get install build-essential
apt-get install python3.4-dev
apt-get install libpython3-dev
pip3 install pyparsing
pip3 install appdirs
pip3 install setuptools==40.1.0
pip3 install cryptography==2.8
pip3 install bcrypt==3.1.7
pip3 install PyNaCl==1.3.0
pip3 install Fabric3==1.14.post1

#install shellcheck
apt-get install
apt install shellcheck
