#!/usr/bin/bash
apt-get update
apt-get install git
apt-get update
apt-get install emacs
apt-get update
apt-get install -y nginx
service nginx restart
apt-get update
apt-get install -y mysql-server
apt-get update
apt-get install -y python3
apt-get update
apt-get install -y nodejs
apt-get update
apt-get install net-tools
apt-get update
apt install curl
